/*
 * This Java source file was generated by the Gradle 'init' task.
 * JSON to java with GSON
 */
package quotes;
import java.lang.reflect.Type;
import java.util.ArrayList;
import com.google.gson.Gson;
import java.io.Reader;
import java.nio.file.*;

import com.google.gson.reflect.TypeToken;
import org.jetbrains.annotations.NotNull;

public class App {
    public ArrayList<Quote> quotes = new ArrayList<Quote>();

    public void fileConverter(String filename){

        try {
            // create Gson instance
            Gson gson = new Gson();

            // create a reader
            Reader reader = Files.newBufferedReader(Paths.get(filename));

            //Convert json obj to java obj ArrayList<Quote>, store in a var
            Type QuoteListType = new TypeToken<ArrayList<Quote>>(){}.getType();

            // convert JSON file to ArrayList by passing in reader and obj type
             quotes = gson.fromJson(reader, QuoteListType);

            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
    //generate random element of non-null array
    public String getRandom(@NotNull ArrayList<Quote> quoteArray){
        int randomIndex = (int) (Math.random() * quoteArray.size());

        return quoteArray.get(randomIndex).toString();
    }

    //if file exist and can be converted from json->java
    //return a quote and arthur (to string)
    public String getGreeting() {

        try {
            fileConverter( "./app/src/main/java/quotes/recentquotes.json");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        String greeting = getRandom(quotes);

        return greeting;
    }

    //driver
    public static void main(String[] args) {
        System.out.println("Quote Of The Day:");
        System.out.println(new App().getGreeting());
    }
}
